### PR TITLE
init function addition

### PR DESCRIPTION
**Pull request by GauravSarkar**
please kindly merge.

### CODE REVIEW

**Comment by knightvertrag** [comment]
Your folder name and GitHub username are not the same. Please change the project folder name.

**Comment by GauravSarkar** [comment]
changed the project folder name.please merge

**Comment by knightvertrag** [comment]
The previous folder still exists, so all of your files have been duplicated. Please delete the previous folder.

**Comment by GauravSarkar** [comment]
i couldn't figure out how to delete the folder,so I closed this PR and submitted fresh PR.

**Pull request closed without merging**
